/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.Conexion;
//import java.beans.Statement;
import java.sql.Statement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author L
 */
public class Articulos extends javax.swing.JFrame {

    /**
     * Creates new form Articulos
     */
    public Articulos() {
        initComponents();
        MostrarArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Statement st = null;
    ResultSet rs = null;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EditarBoton = new javax.swing.JButton();
        AñadirBoton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtFieldNumSerie = new javax.swing.JTextField();
        TxtFieldMarca = new javax.swing.JTextField();
        TxtFieldModelo = new javax.swing.JTextField();
        ComBoxUbicacion = new javax.swing.JComboBox<>();
        ComBoxCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        InicioBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel5.setText("Número de serie");

        EditarBoton.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        EditarBoton.setText("Editar");
        EditarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarBotonMouseClicked(evt);
            }
        });
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        AñadirBoton.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        AñadirBoton.setText("Añadir");
        AñadirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirBotonMouseClicked(evt);
            }
        });
        AñadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirBotonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(243, 228, 111));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel6.setText("Categoría");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel7.setText("Marca");

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel8.setText("Modelo");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel9.setText("Ubicación");

        TxtFieldNumSerie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldNumSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNumSerieActionPerformed(evt);
            }
        });

        TxtFieldMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldMarcaActionPerformed(evt);
            }
        });

        TxtFieldModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldModeloActionPerformed(evt);
            }
        });

        ComBoxUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComBoxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salón A", "Salón B", "Salón C", "Salón D", "Salón E", "Salón F", "Salón G", "Bodega" }));

        ComBoxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU", "Regulador", "Impresora", "Monitor", "Teclado", "Ratón" }));

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. de Serie", "Marca", "Modelo", "Categoría", "Ubicación"
            }
        ));
        TablaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaArticulos);

        InicioBoton.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        InicioBoton.setText("Inicio");
        InicioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioBotonMouseClicked(evt);
            }
        });
        InicioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBotonActionPerformed(evt);
            }
        });

        BorrarBoton.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        BorrarBoton.setText("Borrar");
        BorrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarBotonMouseClicked(evt);
            }
        });
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel10.setText("Artículos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(AñadirBoton)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtFieldNumSerie)
                                .addComponent(TxtFieldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(TxtFieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(ComBoxUbicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InicioBoton)
                                    .addComponent(EditarBoton))
                                .addGap(13, 13, 13)
                                .addComponent(BorrarBoton)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(103, 103, 103)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(886, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComBoxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditarBoton)
                            .addComponent(BorrarBoton)
                            .addComponent(AñadirBoton))
                        .addGap(33, 33, 33)
                        .addComponent(InicioBoton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void MostrarArticulos(){
        
       String sql = "SELECT * FROM ARTICULO; ";
        
        try {
            
            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
//            st = obConect.estableceConexion().createStatement(); 
            st = conectar.estableceConexion().createStatement();
            
            //Se ejecuta la consulta sql
             rs = st.executeQuery(sql);
             
             TablaArticulos.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "ERROR al MOSTRAR contenido de la tabla: \n" + e.toString());
            
        }
        
    }
   
    public void Limpiar(){
                TxtFieldNumSerie.setText("");
                TxtFieldMarca.setText("");
                TxtFieldModelo.setText("");
    }
    
    private void TxtFieldNumSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNumSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNumSerieActionPerformed

    private void TxtFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldMarcaActionPerformed

    private void TxtFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldModeloActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarBotonActionPerformed

    private void AñadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirBotonActionPerformed

    private void InicioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void AñadirBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirBotonMouseClicked

        Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
        
        String consulta = ("INSERT INTO ARTICULO (numero_serie, marca, modelo, categoria, ubicacion) VALUES (?, ?, ?, ?, ?);");  //Se realiza la consulta. Se van a incorporar los valores
        
        try {
            CallableStatement cs = conectar.estableceConexion().prepareCall(consulta);
            
            cs.setString(1, TxtFieldNumSerie.getText());//Se llama a la variable
            cs.setString(2, TxtFieldMarca.getText());
            cs.setString(3, TxtFieldModelo.getText());
            cs.setString(4, ComBoxCategoria.getSelectedItem().toString());
            cs.setString(5, ComBoxUbicacion.getSelectedItem().toString());

            int row = cs.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Se AÑADIO correctamente");
            
            MostrarArticulos();
            
            Limpiar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR al AÑADIR: " + e.toString());
        }
        
        
    }//GEN-LAST:event_AñadirBotonMouseClicked

    private void BorrarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBotonMouseClicked
       
        if (TxtFieldNumSerie.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "INGRESE el artículo a ser BORRADO");
            
        } //if
        
        else{

            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
            String key = TxtFieldNumSerie.getText();
            
            try {
             
             String consulta = "DELETE FROM ARTICULO WHERE numero_serie =" + key;
                
//                Statement cs = conectar.createStatement();
             CallableStatement cs = conectar.estableceConexion().prepareCall(consulta); 
             
             cs.executeUpdate(consulta);
             
             MostrarArticulos(); 
             
             JOptionPane.showMessageDialog(this, "Artículo BORRADO");
             
             Limpiar();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR al BORRAR artículo: " + e.toString());
            }
            
        }//else

    }//GEN-LAST:event_BorrarBotonMouseClicked

    private void TablaArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaArticulosMouseClicked
     
        DefaultTableModel model = (DefaultTableModel)TablaArticulos.getModel();
        int Indice = TablaArticulos.getSelectedRow();
        
        TxtFieldNumSerie.setText(model.getValueAt(Indice, 0).toString());
        TxtFieldMarca.setText(model.getValueAt(Indice, 1).toString());
        TxtFieldModelo.setText(model.getValueAt(Indice, 2).toString());

    }//GEN-LAST:event_TablaArticulosMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        System.exit(0);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void EditarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBotonMouseClicked
        
        if (TxtFieldNumSerie.getText().isEmpty() || TxtFieldMarca.getText().isEmpty() || TxtFieldModelo.getText().isEmpty()) {
          
            JOptionPane.showMessageDialog(this, "Datos incompletos");
            
        } else {
            
            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
            try {
                //numero_serie, marca, modelo, categoria, ubicacion
                String consulta = "UPDATE ARTICULO SET marca ='"+TxtFieldMarca.getText()+"', " + 
                                                       "modelo ='"+TxtFieldModelo.getText()+"', " +
                                                       "categoria ='"+ComBoxCategoria.getSelectedItem().toString()+"', " +
                                                       "ubicacion ='"+ComBoxUbicacion.getSelectedItem().toString()+"'" +
                                                       "WHERE numero_serie ="+TxtFieldNumSerie.getText();
 
                CallableStatement cs = conectar.estableceConexion().prepareCall(consulta); 
                
                
//            cs.setString(1, TxtFieldMarca.getText());
//            cs.setString(2, TxtFieldModelo.getText());
//            cs.setString(3, ComBoxCategoria.getSelectedItem().toString());
//            cs.setString(4, ComBoxUbicacion.getSelectedItem().toString());
//            cs.setString(5, TxtFieldNumSerie.getText()); 
                
            cs.executeUpdate(consulta);   
            
            JOptionPane.showMessageDialog(this, "Artículo MODIFICADO correctamente");
            MostrarArticulos(); 
            Limpiar();
            
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "ERROR al EDITAR artículo: \n" + e.toString());
                
            }
            
        }
        
    }//GEN-LAST:event_EditarBotonMouseClicked

    private void InicioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioBotonMouseClicked
        
        new Inicio().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_InicioBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JComboBox<String> ComBoxCategoria;
    private javax.swing.JComboBox<String> ComBoxUbicacion;
    private javax.swing.JButton EditarBoton;
    private javax.swing.JButton InicioBoton;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTextField TxtFieldMarca;
    private javax.swing.JTextField TxtFieldModelo;
    private javax.swing.JTextField TxtFieldNumSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
