/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.Conexion;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author L
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        MostrarArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Statement st = null;
    ResultSet rs = null;
    
        public void MostrarArticulos(){
        
       String sql = "SELECT * FROM USUARIO; ";
        
        try {
            
            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
//            st = obConect.estableceConexion().createStatement(); 
            st = conectar.estableceConexion().createStatement();
            
            //Se ejecuta la consulta sql
             rs = st.executeQuery(sql);
             
             TablaUsuarios.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "ERROR al MOSTRAR contenido de la tabla: \n" + e.toString());
            
        }
        
    } //MostrarArticulos
        
            public void Limpiar(){
                TxtFieldNoIdentificacion.setText("");
                TxtFieldNombre.setText("");
                TxtFieldTelefono.setText("");
                TxtFieldCorreo.setText("");
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BotonEditar = new javax.swing.JButton();
        BotonAñadir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtFieldNoIdentificacion = new javax.swing.JTextField();
        TxtFieldNombre = new javax.swing.JTextField();
        TxtFieldTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        BotonInicio = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtFieldCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel5.setText("Num. identificación");

        BotonEditar.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        BotonEditar.setText("Editar");
        BotonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEditarMouseClicked(evt);
            }
        });
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonAñadir.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        BotonAñadir.setText("Añadir");
        BotonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAñadirMouseClicked(evt);
            }
        });
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(243, 228, 111));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel6.setText("Correo");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono");

        TxtFieldNoIdentificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldNoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNoIdentificacionActionPerformed(evt);
            }
        });

        TxtFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNombreActionPerformed(evt);
            }
        });

        TxtFieldTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldTelefonoActionPerformed(evt);
            }
        });

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. identificación", "Nombre", "Teléfono", "Correo"
            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        BotonInicio.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        BotonInicio.setText("Inicio");
        BotonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInicioMouseClicked(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        BotonBorrar.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        BotonBorrar.setText("Borrar");
        BotonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBorrarMouseClicked(evt);
            }
        });
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel10.setText("Usuarios");

        TxtFieldCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(BotonAñadir)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BotonEditar))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtFieldNoIdentificacion)
                                                .addComponent(TxtFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                .addComponent(TxtFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                .addComponent(TxtFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BotonBorrar)
                                            .addComponent(BotonInicio))))
                                .addGap(41, 41, 41)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldNoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAñadir)
                            .addComponent(BotonEditar))
                        .addGap(18, 18, 18)
                        .addComponent(BotonBorrar)
                        .addGap(42, 42, 42)
                        .addComponent(BotonInicio)
                        .addGap(6, 6, 6)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void TxtFieldNoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNoIdentificacionActionPerformed

    private void TxtFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNombreActionPerformed

    private void TxtFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldTelefonoActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void TxtFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldCorreoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BotonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAñadirMouseClicked
    

        if (TxtFieldNoIdentificacion.getText().isEmpty() || TxtFieldNombre.getText().isEmpty() || TxtFieldTelefono.getText().isEmpty() || TxtFieldCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos incompletos");
        } 
        
        else {
            
            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
//            String consulta = ("INSERT INTO USUARIO (NumIdentificacion, Nombre, Telefono, Correo) VALUES (?, ?, ?, ?);");  //Se realiza la consulta. Se van a incorporar los valores
String consulta = ("INSERT INTO USUARIO (NumIdentificacion, Nombre, Telefono, Correo) VALUES (?, ?, ?, ?);");  //Se real
            try {
            
            CallableStatement cs = conectar.estableceConexion().prepareCall(consulta);
            
            cs.setString(1, TxtFieldNoIdentificacion.getText());//Se llama a la variable
            cs.setString(2, TxtFieldNombre.getText());
            cs.setString(3, TxtFieldTelefono.getText());
            cs.setString(4, TxtFieldCorreo.getText());

            int row = cs.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Se AÑADIO correctamente");
            
            MostrarArticulos();
            
            Limpiar();
                
            } 
            catch (Exception e) {
                
                 JOptionPane.showMessageDialog(null, "ERROR al AÑADIR \n: " + e.toString());
                
            }
            
        }//else
    


    }//GEN-LAST:event_BotonAñadirMouseClicked

    private void BotonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseClicked
               new Jefe().setVisible(true);
               this.dispose();
    }//GEN-LAST:event_BotonInicioMouseClicked

    private void BotonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEditarMouseClicked
        
                if (TxtFieldNoIdentificacion.getText().isEmpty() || TxtFieldNombre.getText().isEmpty() || TxtFieldTelefono.getText().isEmpty() || TxtFieldCorreo.getText().isEmpty()) {
          
            JOptionPane.showMessageDialog(this, "Datos incompletos");
            
        } else {
            
            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
            try {
                //numero_serie, marca, modelo, categoria, ubicacion
                String consulta = "UPDATE USUARIO SET Nombre ='"+TxtFieldNombre.getText()+"', " + 
                                                       "Telefono ='"+TxtFieldTelefono.getText()+"', " +
                                                       "Correo ='"+TxtFieldCorreo.getText()+"' " +
                                                       "WHERE NumIdentificacion = '"+TxtFieldNoIdentificacion.getText() + "' ";
 
                CallableStatement cs = conectar.estableceConexion().prepareCall(consulta); 
                
                
            cs.executeUpdate(consulta);   
            
            JOptionPane.showMessageDialog(this, "Usuario MODIFICADO correctamente");
            MostrarArticulos(); 
            Limpiar();
            
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "ERROR al EDITAR usuario: \n" + e.toString());
                
            }
            
        }        
                
                
    }//GEN-LAST:event_BotonEditarMouseClicked

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
  
        DefaultTableModel model = (DefaultTableModel)TablaUsuarios.getModel();
        int Indice = TablaUsuarios.getSelectedRow();
        
        TxtFieldNoIdentificacion.setText(model.getValueAt(Indice, 0).toString());
        TxtFieldNombre.setText(model.getValueAt(Indice, 1).toString());
        TxtFieldTelefono.setText(model.getValueAt(Indice, 2).toString());
        TxtFieldCorreo.setText(model.getValueAt(Indice, 3).toString());
        
        
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void BotonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrarMouseClicked
        
        if (TxtFieldNoIdentificacion.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "INGRESE el usuario a ser BORRADO");
            
        } //if
        
        else{

            Conexion conectar = new Conexion(); //Se crea un objeto de la clase conexion para establecer la conexion
            
            String key = TxtFieldNoIdentificacion.getText();
            
            try {
             
             String consulta = "DELETE FROM USUARIO WHERE NumIdentificacion =" + key;
                
//                Statement cs = conectar.createStatement();
             CallableStatement cs = conectar.estableceConexion().prepareCall(consulta); 
             
             cs.executeUpdate(consulta);
             
             MostrarArticulos(); 
             
             JOptionPane.showMessageDialog(this, "Usuario BORRADO");
             
             Limpiar();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR al BORRAR usuario: \n" + e.toString());
            }
            
        }//else
        
    }//GEN-LAST:event_BotonBorrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonInicio;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JTextField TxtFieldCorreo;
    private javax.swing.JTextField TxtFieldNoIdentificacion;
    private javax.swing.JTextField TxtFieldNombre;
    private javax.swing.JTextField TxtFieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
